### ISSUE TITLE
Is there a Light-Weight Decoder Too?

### ISSUE THREAD

**Issue by kells1986** [ChaoningZhang/MobileSAM#1]
So I cloned the repo and worked through the notebook. Do I understand correctly that there's a lightweight image encoded based on TinyViT, but you still need to use the fullsize SAM decoder? I had to download the `sam_vit_h_4b8939.pth` file, which is 2.4GB. 

Am I using this wrong? Or are there smaller decoder models?

**Comment by ChaoningZhang** [comment]
Thanks very much for your interest in our work. Our MobileSAM uses exactly the same lightweight decoder (including pretrained weights) as the original SAM. **The decoder is less than 4M, and in total our MobileSAM has less than 10M parameters**. We will update our code so that the user can directly use our lightweight MobileSAM without the need to download sam_vit_h (Stay tuned!). If you have more questions please let us know.

**Comment by kells1986** [comment]
Excellent, I'll pull your changes and take a look today. Great work, thanks for sharing!

**Comment by ChaoningZhang** [comment]
> Excellent, I'll pull your changes and take a look today. Great work, thanks for sharing!

Thanks for your interest in our work. Since your issues are addressed, we close it. Please feel free to raise new issues.
